### ISSUE TITLE
Update `scenario_data_years.csv`

### ISSUE THREAD

**Issue by talassio** [homodata/bsp#10]
Hay dos versiones del mismo archivo  `scenario_data_years.csv`.

 1. El archivo correcto esta en `region2020/conf/scenario_data_years.csv`
 2. El segundo archivo no usado esta en `region2020/scenario_data_years.csv` y lo renombré a  `region2020/scenario_data_years.csv.disabled`, si tienes cambios en este fichero, los puedes pasar para el correcto bajo la carpeta `conf/`

Es necesaro verificar que los años en las capas `*_bsp2020.csv` correspondan a los años reportados en el fichero `region2020/conf/scenario_data_years.csv`.

**Una vez que esto esté actualizado seria bueno eliminar el archivo `scenario_data_years.csv.disabled`.**

**Comment by lelysbravo** [comment]
La capa scenarios-data_years fue revisada y actualizada.
