### ISSUE TITLE
Revisar meta CP

### ISSUE THREAD

**Issue by lelysbravo** [homodata/bsp#11]
No calcula scores para la region 2. Los  valores de  hab_saltmarsh son cero para la region 2 pero hab_mangrove es distinto de cero.

**Comment by talassio** [comment]
This is linked to #12

**Comment by talassio** [comment]
La meta CP hacía diferencia entre "mangrove_inland1k" y "mangrove_offshore", y la en `functions.R::CP` se acumulaban estas dos capas en extent "mangrove". Por otro lado, los datos actuales BSP usan
"mangrove" sin distinción de 1km inland u offshore, así que la acumulación de estas
dos medidas NA producían NA y por ello desaparecía "mangrove". 

La meta CP fue actualizada para utilizar los datos existentes y los cambios se repotan a continuación.

# OLD
```{R}
> CP(layers)
# A tibble: 4 x 4
  region_id goal  dimension    score
      <int> <chr> <chr>        <dbl>
1         1 CP    status    100     
2         2 CP    status    100     
3         1 CP    trend       0.0127
4         2 CP    trend       0     
```

# NEW
## Goal
```
# A tibble: 4 x 4
  region_id goal  dimension    score
      <int> <chr> <chr>        <dbl>
1         1 CP    status    100     
2         2 CP    status    100     
3         1 CP    trend       0.0582
4         2 CP    trend       0.156 
```

## Weights 
```
$ cat element_wts_cp_km2_x_protection_2020.csv

"rgn_id","habitat","extent_rank","layer"
1,"mangrove",11.95076,"element_wts_cp_km2_x_protection"
2,"mangrove",18.99376,"element_wts_cp_km2_x_protection"
1,"saltmarsh",78.2784,"element_wts_cp_km2_x_protection"
2,"saltmarsh",0.003,"element_wts_cp_km2_x_protection"
```
