### ISSUE TITLE
rgn_id does not exist

### ISSUE THREAD

**Issue by lelysbravo** [homodata/bsp#6]
With the new functions.R version from the latest global assessment, and all global layers updated for Peru, the following error pops up:
![image](https://user-images.githubusercontent.com/7624995/129418597-7ebd2607-1da9-4d65-a3ee-88a675c5aa7e.png)
Please check!

**Comment by lelysbravo** [comment]
We solved it!

**Comment by talassio** [comment]
Wow! that was fast!

**Comment by talassio** [comment]
Fixed by @lelysbravo
